project/messages/models.py
from project import db

class Message(db.Model):
  __tablename__ = "messages"

  id = db.Column(db.Integer, primary_key=True)
  msg_text = db.Column(db.String(100), nullable=False)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id')) #has to be primary key here

  def __init__(self, msg_text, user_id):
    self.msg_text = msg_text
    self.user_id = user_id

  def __repr__(self):
    return "The message is: {}".format(self.msg_text)

project/users/models.py
from project import db
from project.messages.models import Message

class User(db.Model):
  __tablename__ = 'users'

  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.Text, unique=True, nullable=False)
  email = db.Column(db.Text, unique=True, nullable=False)
  first_name = db.Column(db.Text)
  last_name = db.Column(db.Text)
  messages = db.relationship('Message', backref='user', lazy='dynamic')

  def __init__(self, username, email, first_name, last_name):
    self.username = username
    self.email = email
    self.first_name = first_name
    self.last_name = last_name

  def __repr__(self):
    return "This user's username is {}, email is {}, first name is {}, and last name is {}".format(self.username, self.email, self.first_name, self.last_name)

project/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms.validators import Length

class MessageForm(FlaskForm):
  msg_text = TextAreaField('Message', validators = [Length(min=1, max=100)], render_kw={"rows": 5, "cols": 40})

project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import Length, Email

class UserForm(FlaskForm): #this is inheriting from FlaskForm class
  username = StringField('Username', validators=[Length(min=1)]) #Unique(User, User.username, message="there is already an account with that username")])
  email = StringField('Email', validators = [Length(min=5, max=35), Email()])
  first_name = StringField('First Name', validators = [Length(min=1)])
  last_name = StringField('Last Name', validators =[Length(min=1)])

app.py
from project import app
import os

# If we are in production, make sure we DO NOT use the debug mode
if os.environ.get('ENV') == 'production':
  debug = False
else:
  debug = True

if __name__ == '__main__':
  app.run(debug=debug)

project/__init__.py
from flask import Flask, url_for, redirect
from flask_sqlalchemy import SQLAlchemy
from flask_modus import Modus
import os

app = Flask(__name__)
modus = Modus(app)

app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')

app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL') or 'postgres://localhost/user-blueprints'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

from project.users.views import users_blueprint
from project.messages.views import messages_blueprint

app.register_blueprint(users_blueprint, url_prefix='/users')
app.register_blueprint(messages_blueprint, url_prefix='/users/<int:user_id>/messages')


@app.route('/')
def root():
  return redirect(url_for('users.index'))

project/messages/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from project.messages.models import Message
from project.users.models import User
from project.messages.forms import MessageForm
from project import db
from sqlalchemy.exc import IntegrityError

messages_blueprint = Blueprint(
  'messages',
  __name__,
  template_folder='templates'
)

@messages_blueprint.route('/', methods=['GET', 'POST'])
def index(user_id):
  user = User.query.get(user_id)
  messages = user.messages
  if request.method == 'POST':
    form = MessageForm(request.form)
    if form.validate():
      try:
        new_msg = Message(form.msg_text.data, user_id)
        db.session.add(new_msg)
        db.session.commit()
        flash('You added the message: "' + form.msg_text.data + '"')
        return redirect(url_for('messages.index', user_id=user_id))

      #if violates unique field for username/email
      except IntegrityError as e:
        if (str(e.orig.pgerror).find('username_key') != -1):
          flash("Please enter a different username. This user already exists.")
        else:
          flash("Please enter a different email. This email already exists.")
    return render_template('messages/new.html', user=user, form=form)

  return render_template('messages/index.html', messages=messages, user=user)

@messages_blueprint.route('/new')
def new(user_id):
  user = User.query.get(user_id)
  form = MessageForm()
  return render_template('messages/new.html', user=user, form=form)

@messages_blueprint.route('/<int:msg_id>/edit')
def edit(user_id, msg_id):
  found_user = User.query.get(user_id)
  selected_message = Message.query.get_or_404(msg_id)
  form = MessageForm(obj=selected_message)
  return render_template('messages/edit.html', user=found_user, message=selected_message, form=form)

@messages_blueprint.route('/<int:msg_id>', methods=['GET', 'PATCH', 'DELETE'])
def show(user_id,msg_id):
  found_user = User.query.get_or_404(user_id)
  selected_message = Message.query.get_or_404(msg_id)
  if request.method == b'PATCH':
    form = MessageForm(request.form, obj=selected_message)
    if form.validate():
      form.populate_obj(selected_message)
      db.session.add(selected_message)
      db.session.commit()
      flash('You edited the message. "' + selected_message.msg_text + '"')
      return redirect(url_for('messages.index', user_id=found_user.id))
    return render_template('messages/edit.html', user=found_user, message=selected_message, form=form)

  if request.method == b'DELETE':
    db.session.delete(selected_message)
    db.session.commit()
    flash('You deleted the message: "' + selected_message.msg_text + '"')
    return redirect(url_for('messages.index', user_id=found_user.id))

  #NO GET HERE FOR SHOW

project/users/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from project.users.models import User
from project.users.forms import UserForm
from project import db
from sqlalchemy.exc import IntegrityError

users_blueprint = Blueprint(
  'users',
  __name__,
  template_folder='templates'
)

@users_blueprint.route('/', methods=['GET', 'POST'])
def index():
  if request.method == 'POST':
    form = UserForm(request.form)
    if form.validate():
      try:
        new_user = User(form.username.data, form.email.data, form.first_name.data, form.last_name.data)
        db.session.add(new_user)
        db.session.commit()
        flash("You added the user: " + new_user.username)
        return redirect(url_for('users.index'))

      #if violates unique field for username/email
      except IntegrityError as e:
        if (str(e.orig.pgerror).find('username_key') != -1):
          flash("Please enter a different username. This user already exists.")
        else:
          flash("Please enter a different email. This email already exists.")
    return render_template('users/new.html', form=form)

  users = User.query.all()
  return render_template('users/index.html', users = users)

@users_blueprint.route('/new')
def new():
  form = UserForm()
  return render_template('users/new.html', form=form)

@users_blueprint.route('/<int:user_id>/edit')
def edit(user_id):
  user = User.query.get(user_id)
  form = UserForm(obj=user)
  return render_template('users/edit.html', form=form, user=user)

@users_blueprint.route('/<int:user_id>', methods=['GET', 'PATCH', 'DELETE'])
def show(user_id):
  found_user = User.query.get_or_404(user_id)
  if request.method == b'PATCH':
    form = UserForm(request.form)
    if form.validate():
      try:
        form.populate_obj(found_user)
        db.session.add(found_user)
        db.session.commit()
        flash("You edited this user.")
        return redirect(url_for('users.show', user_id = found_user.id))

      #if violates unique field for username/email
      except IntegrityError as e:
        if (str(e.orig.pgerror).find('username_key') != -1):
          flash("Please enter a different username. This user already exists.")
        else:
          flash("Please enter a different email. This email already exists.")
        db.session.rollback()
      #if form isn't validating
    return render_template('users/edit.html', user=found_user, form=form)

  if request.method == b'DELETE':
    db.session.delete(found_user)
    db.session.commit()
    flash("You deleted the user: " + found_user.username)
    return redirect(url_for('users.index'))

  return render_template('users/show.html', user=found_user) 

project/messages/templates/messages/edit.html
{% extends 'base.html' %}

{% block title %}
Message: Edit
{% endblock %}

{% block content %}

<div class="container-fluid">
  {% if get_flashed_messages() %}
    <div class="alert alert-warning">
      {% for msg in get_flashed_messages() %}
        <p class="text-center">{{ msg }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <h1>Edit Message for User: {{ user.username }}</h1>

  <form action="{{url_for('messages.show', user_id=user.id, msg_id=message.id)}}?_method=PATCH" method="POST">
    {{ form.csrf_token }}
    {% for field in form %}
      {% if field.name != 'csrf_token' %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-lg">
            {{ field.label }}
          </label> 
          <div class="col-sm-10">
            {{ field }}
            <span>
              {% if field.errors %}
                {% for error in field.errors %}
                  {{ error }}
                {% endfor %}
              {% endif %}
            </span>
          </div>
        </div>      
      {% endif %}
    {% endfor %}
    <input class="btn btn-default btnCustom" type="submit" value="Edit">
    <a class="btn btn-default btnCustom" href="{{url_for('messages.index', user_id=user.id)}}">Cancel</a> 
  </form>

  <br>
  
  <p>
    <a class="btn btn-default btnCustom" href="{{url_for('users.index')}}"> Back to All Users
    </a>
  </p>

</div>
{% endblock %}

project/messages/templates/messages/index.html
{% extends 'base.html' %}

{% block title %}
Messages: {{user.username}} 
{% endblock %}

{% block content %}
<div class="container-fluid">
  {% if get_flashed_messages() %}
    <div class="alert alert-warning">
      {% for msg in get_flashed_messages() %}
        <p class="text-center">{{ msg }}</p>
      {% endfor %}
    </div>
  {% endif %}
  <h1>Messages for User: {{user.username}}</h1>
</div>

<div class="container-fluid">
    <a class="btn btn-default btnCustom" href="{{url_for('messages.new', user_id=user.id)}}">
      Add a Message
    </a>
    <a class="btn btn-default btnCustom" href="{{url_for('users.show', user_id=user.id)}}">
      Back to User
    </a>
</div>

<br>

<div class="container-fluid">
  {% if messages.all() == [] %}
    <p>There are no messages for this user.</p>
  {% endif %}
  {% if messages.all() != [] %}
    <table class="table table-bordered">
      <thead>
        <tr>
          <th></th>
          <th>Message</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for message in messages %}
          <tr class="{{ loop.cycle('odd', 'even') }}">
            <td>{{ loop.index }}</td>
            <td>{{ message.msg_text }}</td>
            <td>
              <form action="{{url_for('messages.show', user_id=user.id, msg_id=message.id)}}?_method=DELETE" method="POST">
                <a class="btn btn-default btnCustom" href="{{url_for('messages.show', user_id=user.id, msg_id=message.id)}}?_method=PATCH" method='PATCH'>
                  Edit
                </a>   
                <input class="btn btn-default btnCustom" type="submit" value="Delete">
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
</div>
{% endblock %}

project/messages/templates/messages/new.html
{% extends 'base.html' %}

{% block title %}
Message: Add
{% endblock %}

{% block content %}
<div class="container-fluid">
  {% if get_flashed_messages() %}
    <div class="alert alert-warning">
      {% for msg in get_flashed_messages() %}
        <p class="text-center">{{ msg }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <h1>Add a Message: for {{user.username}}</h1>

  <form action="{{url_for('messages.index', user_id=user.id)}}" method="POST">
    {{ form.csrf_token }}
    {% for field in form %}
      {% if field.name != 'csrf_token' %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-lg">
            {{ field.label }}
          </label> 
          <div class="col-sm-8">
            {{ field }}
            <span class="messageField">
              {% if field.errors %}
                {% for error in field.errors %}
                  {{ error }}
                {% endfor %}
              {% endif %}
            </span>
          </div>
        </div>      
      {% endif %}
    {% endfor %}
    <input class="btn btn-default btnCustom" type="submit" value="Add Message">
    <a class="btn btn-default btnCustom" href="{{url_for('messages.index', user_id = user.id)}}">Cancel</a> 
  </form>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Users App</title>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

project/users/templates/users/edit.html
{% extends 'base.html' %}

{% block title %}
User: Edit
{% endblock %}

{% block content %}
<div class="container-fluid">
  {% if get_flashed_messages() %}
    <div class="alert alert-warning">
      {% for msg in get_flashed_messages() %}
        <p class="text-center">{{ msg }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <h1>Edit the User</h1>

  <form action="{{url_for('users.show', user_id=user.id)}}?_method=PATCH" method="POST">
    {{ form.csrf_token }}
    {% for field in form %}
      {% if field.name != 'csrf_token' %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-lg">
            {{ field.label }}
          </label> 
          <div class="col-sm-10">
            {{ field }}
            <span>
              {% if field.errors %}
                {% for error in field.errors %}
                  {{ error }}
                {% endfor %}
              {% endif %}
            </span>
          </div>
        </div>      
      {% endif %}
    {% endfor %}
    <input class="btn btn-default btnCustom" type="submit" value="Edit">
    <a class="btn btn-default btnCustom" href="{{url_for('users.show', user_id=user.id)}}">Cancel</a> 
  </form>

</div>
{% endblock %}

project/users/templates/users/index.html
{% extends 'base.html' %}
{% block title %}
Users
{% endblock %}

{% block content %}
<div class="container-fluid">
  {% if get_flashed_messages() %}
    <div class="alert alert-warning">
      {% for msg in get_flashed_messages() %}
        <p class="text-center">{{ msg }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <h1>Users List <a class="btn btn-default btnCustom" href="{{url_for('users.new')}}">Add a User</a></h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th></th>
        <th>Username</th>
        <th>First Name</th>
        <th>Last Name</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr class="{{ loop.cycle('odd', 'even') }}">
          <td>{{ loop.index }}</td>
          <td><a href="{{url_for('users.show', user_id=user.id)}}">{{user.username}}</a></td>
          <td>{{user.first_name}}</td>
          <td>{{user.last_name}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
{% endblock %}

project/users/templates/users/new.html
{% extends 'base.html' %}

{% block title %}
User: Add
{% endblock %}

{% block content %}

<div class="container-fluid">
  {% if get_flashed_messages() %}
    <div class="alert alert-warning">
      {% for msg in get_flashed_messages() %}
        <p class="text-center">{{ msg }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <h1>Add a User</h1>

  <form action="{{url_for('users.index')}}" method="POST">
    {{ form.csrf_token }}
    {% for field in form %}
      {% if field.name != 'csrf_token' %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-lg">
            {{ field.label }}
          </label> 
          <div class="col-sm-10">
            {{ field }}
            <span>
              {% if field.errors %}
                {% for error in field.errors %}
                  {{ error }}
                {% endfor %}
              {% endif %}
            </span>
          </div>
        </div>      
      {% endif %}
    {% endfor %}
    <input class="btn btn-default btnCustom" type="submit" value="Add user">
    <a class="btn btn-default btnCustom" href="{{url_for('users.index')}}">Cancel</a> 
  </form>

</div>
{% endblock %}

project/users/templates/users/show.html
{% extends 'base.html' %}

{% block title %}
User Details
{% endblock %}

{% block content %}
<div class="container-fluid">
  {% if get_flashed_messages() %}
    <div class="alert alert-warning">
      {% for msg in get_flashed_messages() %}
        <p class="text-center">{{ msg }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <h1>Details for user: {{ user.username }}
    <a class="btn btn-default btnCustom" href="{{url_for('users.index')}}"> All Users
    </a>
  </h1>
  <br>
</div>

<div class="container-fluid">
  <div class="row col-sm-8">
  <table class="table table-bordered">
    <tbody>
      <tr class="odd">
        <td><b>Name</b></td>
        <td>{{user.username}}</td>  
      </tr>
      <tr class="even">
        <td><b>Email</b></td>
        <td>{{user.email}}</td>  
      </tr>
      <tr class="odd">
        <td><b>First Name</b></td>
        <td>{{user.first_name}}</td>  
      </tr>
      <tr class="even">
        <td><b>Last Name</b></td>
        <td>{{user.last_name}}</td>  
      </tr>
    </tbody>
  </table>
  </div>
</div>

<div class="container-fluid">
  <form action="{{url_for('users.show', user_id=user.id)}}?_method=DELETE" method="POST">
    <a class="btn btn-default btnCustom" href="{{url_for('users.edit', user_id=user.id)}}">
      Edit
    </a>
    <input class="btn btn-default btnCustom" type="submit" value="Delete"></input>
    <a class="btn btn-default btnCustom" href="{{url_for('messages.index', user_id=user.id)}}">See User's Messages</a>
  </form>
</div>

{% endblock %}